# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ed31ec0d10189892ba5555a327ceae41e328da3a6c581d8a5822869367e2e040491993487ae36e8f9d2b398a1829dee36eed9dbe4c11ce80c220c2212162e7

test:
  secret_key_base: 0a59c2588695bfb6940090d69b231b6c9539f7e860ea34a13fa6c56bc50f0994e4294d61d09cd07ab2f421d3a02999335ca38738e8986645a91d42c51a53060a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
